id: P003084
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:39:21.925072
source_metadata:
  id: bdr:W1PD105801
  title: དཔལ་དོན་གྲུབ་རྒྱལ་ལ་ཞིབ་འཇུག་བྱས་པའི་དཔྱད་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    a702a0d1a8a34bf0a789d0ed89367ca0:
      image_group_id: I1PD105803
      title: ''
      volume_number: 1
      total_pages: 693
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
